name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: 'pip'

    - run: make deps

    - name: Build static blog pageset
      run: make build

    - name: Init new repo and commit files
      run: |
        cd build
        git init --initial-branch=main
        git add -A
        git config --local user.email "richardjharris@gmail.com"
        git config --local user.name "Richard Harris"
        git commit -m 'deploy'

    - name: Force push to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: ./build
